"""init full schema

Revision ID: 2a2e54da3c17
Revises: 
Create Date: 2026-03-04 22:01:06.928050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a2e54da3c17'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('chain', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wallet', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wallet_address'), ['address'], unique=True)
        batch_op.create_index(batch_op.f('ix_wallet_chain'), ['chain'], unique=False)
        batch_op.create_index(batch_op.f('ix_wallet_id'), ['id'], unique=False)

    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(), nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=False),
    sa.Column('from_address', sa.String(), nullable=False),
    sa.Column('to_address', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('gas', sa.Float(), nullable=False),
    sa.Column('gas_price', sa.Float(), nullable=False),
    sa.Column('block_number', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaction_hash'), ['hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_transaction_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_transaction_hash'))

    op.drop_table('transaction')
    with op.batch_alter_table('wallet', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wallet_id'))
        batch_op.drop_index(batch_op.f('ix_wallet_chain'))
        batch_op.drop_index(batch_op.f('ix_wallet_address'))

    op.drop_table('wallet')
    # ### end Alembic commands ###
