"""update holder transaction event for usdc transfers

Revision ID: 9cd8f15fd150
Revises: 9eba3009b0b5
Create Date: 2026-03-17 22:43:57.453484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cd8f15fd150'
down_revision: Union[str, Sequence[str], None] = '9eba3009b0b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('HolderTransactionEvent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('value_raw', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('token_symbol', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('token_decimals', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('contract_address', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('source', sa.String(), nullable=False))
        batch_op.drop_constraint(batch_op.f('uq_holder_transaction_hash'), type_='unique')
        batch_op.create_index(batch_op.f('ix_HolderTransactionEvent_from_address'), ['from_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_HolderTransactionEvent_to_address'), ['to_address'], unique=False)
        batch_op.create_unique_constraint('uq_holder_transfer_event', ['holder_id', 'transaction_hash', 'from_address', 'to_address', 'value_raw'])
        batch_op.drop_column('notified_at')
        batch_op.drop_column('value_wei')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('HolderTransactionEvent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('value_wei', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('notified_at', sa.DATETIME(), nullable=True))
        batch_op.drop_constraint('uq_holder_transfer_event', type_='unique')
        batch_op.drop_index(batch_op.f('ix_HolderTransactionEvent_to_address'))
        batch_op.drop_index(batch_op.f('ix_HolderTransactionEvent_from_address'))
        batch_op.create_unique_constraint(batch_op.f('uq_holder_transaction_hash'), ['holder_id', 'transaction_hash'])
        batch_op.drop_column('source')
        batch_op.drop_column('contract_address')
        batch_op.drop_column('token_decimals')
        batch_op.drop_column('token_symbol')
        batch_op.drop_column('value_raw')

    # ### end Alembic commands ###
