"""add holder tracking tables

Revision ID: 9eba3009b0b5
Revises: 2a2e54da3c17
Create Date: 2026-03-05 13:12:25.572794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9eba3009b0b5'
down_revision: Union[str, Sequence[str], None] = '2a2e54da3c17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TrackedHolder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('balance_wei', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('TrackedHolder', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_TrackedHolder_address'), ['address'], unique=True)
        batch_op.create_index(batch_op.f('ix_TrackedHolder_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_TrackedHolder_rank'), ['rank'], unique=False)

    op.create_table('HolderTransactionEvent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('holder_id', sa.Integer(), nullable=False),
    sa.Column('transaction_hash', sa.String(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('from_address', sa.String(), nullable=False),
    sa.Column('to_address', sa.String(), nullable=True),
    sa.Column('value_wei', sa.String(), nullable=False),
    sa.Column('block_number', sa.Integer(), nullable=False),
    sa.Column('block_timestamp', sa.DateTime(), nullable=False),
    sa.Column('notified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['holder_id'], ['TrackedHolder.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('holder_id', 'transaction_hash', name='uq_holder_transaction_hash')
    )
    with op.batch_alter_table('HolderTransactionEvent', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_HolderTransactionEvent_block_number'), ['block_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_HolderTransactionEvent_holder_id'), ['holder_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_HolderTransactionEvent_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_HolderTransactionEvent_transaction_hash'), ['transaction_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('HolderTransactionEvent', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_HolderTransactionEvent_transaction_hash'))
        batch_op.drop_index(batch_op.f('ix_HolderTransactionEvent_id'))
        batch_op.drop_index(batch_op.f('ix_HolderTransactionEvent_holder_id'))
        batch_op.drop_index(batch_op.f('ix_HolderTransactionEvent_block_number'))

    op.drop_table('HolderTransactionEvent')
    with op.batch_alter_table('TrackedHolder', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_TrackedHolder_rank'))
        batch_op.drop_index(batch_op.f('ix_TrackedHolder_id'))
        batch_op.drop_index(batch_op.f('ix_TrackedHolder_address'))

    op.drop_table('TrackedHolder')
    # ### end Alembic commands ###
